### PR TITLE
Add note regarding release_level_backup feature flag to bbr devguide.

### PR DESCRIPTION
**Pull request by edwardecook**
@thereses - please review this change. Thanks!

### CODE REVIEW

**Comment by jncd** [comment]
@edwardecook Hi Ed, Thanks for this PR. What's the difference between a "release author" and a "CF release author" in these notes? If they are the same person, we should just combine these two notes into one and make a bulleted list.  
Stacking notes quickly leads to note fatigue where readers don't read both.

**Comment by ghanna2017** [comment]
Thanks, @edwardecook. Ditto to Jane's question. Is there a difference between "release authors" and "cf release authors"?

**Comment by edwardecook** [comment]
Hi @jncd @ghanna2017, apologies for the delay in getting back to you, "cf release author" corresponds to someone writing a release specifically for OS or Pivotal cloud foundry who therefore needs to take account of the release_level_backup feature flag. Whereas a "release author" is more general

**Comment by ghanna2017** [comment]
@edwardecook great, thanks. That's what I assumed and wrote the note accordingly.

**Pull request merged**
