### PR TITLE
Tweak the nozzle examples section

### PR DESCRIPTION
**Pull request by cholick**

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @cholick 
I'll merge and fix typos.

**Comment by jncd** [comment]
BTW: And what's an "acl" ? as in "* Includes implementation code that adds additional metadata (potentially needed for acl)"
I can't find this term used anywhere else in this doc. I wonder if it should be an acronym for something... but then it would be capitalized...
TIA

**Comment by cholick** [comment]
Yes, it's an acronym (access control list)

**Comment by jncd** [comment]
Coolio, I'll tweak the doc for clarity.

**Pull request merged**
